[workspace]
resolver = "2"
members = ["crates/okiro-core", "crates/okiro"]

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"
authors = ["Michał Czyż <mike@c2yz.com>"]
repository = "https://github.com/eRgo35/okiro"
homepage = "https://github.com/eRgo35/okiro"
readme = "../../README.md"

[workspace.dependencies]
clap = { version = "4.5.50", features = ["derive"] }
colorize = "0.1.0"
config = { version = "0.15.18", features = ["toml"] }
macaddr = "1.0"
socket2 = { version = "0.5", features = ["all"] }
thiserror = "1.0"
webbrowser = "1.0"